tosca.nodes.Container.Application:
    derived_from: tosca.nodes.Root
    description: >
      The TOSCA Container Application node represents an application that requires Container-level virtualization technology.
    requirements:
      - host:
          capability: tosca.capabilities.Container
          node: tosca.nodes.Container
          relationship: tosca.relationships.HostedOn